name: Call building packages
true:
  workflow_call:
    inputs:
      artifact-name:
        description: Unique name for collecting artifacts
        required: true
        type: string
      pkg-names:
        default: '["lightning", "fabric", "pytorch"]

          '
        description: list package names to be build in json format
        required: false
        type: string
defaults:
  run:
    shell: bash
jobs:
  build-packages:
    needs: init
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: pypi
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - run: python -c "print('NB_DIRS=' + str(2 if '${{ matrix.pkg-name }}' == 'pytorch'
        else 1))" >> $GITHUB_ENV
    - name: Build & check package
      uses: ./.github/actions/pkg-check
      with:
        nb-dirs: ${{ env.NB_DIRS }}
        pkg-name: ${{ matrix.pkg-name }}
    - run: 'mkdir pypi/${{ matrix.pkg-name }}

        cp dist/* pypi/${{ matrix.pkg-name }}/

        '
    - uses: actions/upload-artifact@v3
      with:
        include-hidden-files: true
        name: ${{ inputs.artifact-name }}
        path: pypi
    strategy:
      matrix:
        pkg-name: ${{ fromJSON(inputs.pkg-names) }}
      max-parallel: 1
  init:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - run: 'mkdir dist && touch dist/.placeholder

        '
    - id: keep-artifact
      name: Keep artifact
      run: python -c "print('DAYS=' + str(5 if '${{ github.event_name }}'.startswith('pull_request')
        else 0))" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v3
      with:
        include-hidden-files: true
        name: ${{ inputs.artifact-name }}
        path: dist
        retention-days: ${{ steps.keep-artifact.outputs.DAYS }}
