name: Clear cache weekly
true:
  pull_request:
    paths:
    - .github/workflows/call-clear-cache.yml
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      age-days:
        default: 5
        description: setting the age of caches in days to be dropped
        required: true
        type: number
      pattern:
        default: pip-|conda
        description: pattern for cleaning cache
        required: false
        type: string
jobs:
  cron-clear:
    if: github.event_name == 'schedule' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    uses: Lightning-AI/utilities/.github/workflows/cleanup-caches.yml@v0.11.7
    with:
      age-days: 7
      dry-run: ${{ github.event_name == 'pull_request' }}
      pattern: latest|docs
      scripts-ref: v0.11.7
  direct-clear:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    uses: Lightning-AI/utilities/.github/workflows/cleanup-caches.yml@v0.11.7
    with:
      age-days: ${{ fromJSON(inputs.age-days) || 0 }}
      dry-run: ${{ github.event_name == 'pull_request' }}
      pattern: ${{ inputs.pattern || 'pypi_wheels' }}
      scripts-ref: v0.11.7
