name: RTFD Preview
true:
  pull_request_target:
    types:
    - opened
permissions:
  pull-requests: write
jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - uses: readthedocs/actions/preview@v1
      with:
        project-slug: pytorch-lightning
