name: Check Schema
true:
  pull_request:
    branches:
    - master
    - release/*
  push:
    branches:
    - master
    - release/*
jobs:
  check:
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@v0.11.7
    with:
      azure-dir: ''
