name: cleanup caches on a branch
true:
  pull_request:
    types:
    - closed
jobs:
  pr-cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Cleanup
      run: "gh extension install actions/gh-actions-cache\n\nREPO=${{ github.repository\
        \ }}\nBRANCH=\"refs/pull/${{ github.event.pull_request.number }}/merge\"\n\
        \necho \"Fetching list of cache key\"\ncacheKeysForPR=$(gh actions-cache list\
        \ -R $REPO -B $BRANCH | cut -f 1 )\n\n## Setting this to not fail the workflow\
        \ while deleting cache keys.\nset +e\necho \"Deleting caches...\"\nfor cacheKey\
        \ in $cacheKeysForPR\ndo\n    gh actions-cache delete $cacheKey -R $REPO -B\
        \ $BRANCH --confirm\ndone\necho \"Done\"\n"
