name: Code check
true:
  pull_request:
    branches:
    - master
    - release/*
    paths:
    - .actions/*
    - .github/workflows/code-checks.yml
    - requirements/**
    - src/**
    - pyproject.toml
    - '!requirements/docs.txt'
    - '!requirements/*/docs.txt'
    - '!*.md'
    - '!**/*.md'
  push:
    branches:
    - master
    - release/*
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
defaults:
  run:
    shell: bash
jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Mypy cache
      uses: actions/cache@v4
      with:
        key: mypy-${{ hashFiles('requirements/typing.txt') }}
        path: .mypy_cache
    - env:
        FREEZE_REQUIREMENTS: 1
      name: Install dependencies
      run: 'pip install -e ''.[pytorch-all,fabric-all]'' -r requirements/typing.txt

        pip list

        '
      timeout-minutes: 20
    - name: Check typing
      run: mypy
