name: Label Pull Requests
true:
- pull_request_target
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/label-change.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
