name: Probot
true:
  issues:
    types:
    - labeled
  pull_request:
    types:
    - labeled
    - ready_for_review
jobs:
  auto-cc:
    if: github.event_name == 'issue' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: Lightning-AI/probot@v1
      with:
        job: auto-cc
    timeout-minutes: 5
