name: Probot
true:
  pull_request:
    types:
    - opened
    - reopened
    - ready_for_review
    - synchronize
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
jobs:
  required-jobs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: Lightning-AI/probot@v5.4
      with:
        interval: 180
        job: check-group
        maintainers: Lightning-AI/lai-frameworks
        owner: carmocca
        timeout: 60
    timeout-minutes: 61
